name: Github Action Demo
on: [ push]
job: 
  Test:
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v2
      - run: echo "The code was actually triggered by a ${{github.event_name}} event."
      - run: python main.py