name: Github Action Demo
on: [ push]
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: echo "The code was actually triggered by a ${{github.event_name}} event."
      - run: python main.py
